name: learn-github-actions
run-name: ${{ github.actor }} is learning GitHub Actions
on:
  push:
    branches:
      - main
    
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install
      - run: npm run build
      - run: git config --global user.name 'dreamer20'
      - run: git config --global user.email 'gv4alex@gmail.com'
      - run: git fetch --all
      - run: git branch -r
      - run: git checkout dist --
      - run: git status
      - run: cp -r dist/* .
      - run: git status
      - run: cp index.html 404.html
      - run: git add .
      - run: git commit -m "Update app"
      - run: git push origin dist
